# Embedded file name: UI_MainWindow.pyo
from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8('MainWindow'))
        MainWindow.resize(790, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8('./res/surf.ico')), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8('centralwidget'))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8('tabWidget'))
        self.tab_surf = QtGui.QWidget()
        self.tab_surf.setObjectName(_fromUtf8('tab_surf'))
        self.groupBox_urlsurf = QtGui.QGroupBox(self.tab_surf)
        self.groupBox_urlsurf.setGeometry(QtCore.QRect(400, 10, 381, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_urlsurf.sizePolicy().hasHeightForWidth())
        self.groupBox_urlsurf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_urlsurf.setFont(font)
        self.groupBox_urlsurf.setObjectName(_fromUtf8('groupBox_urlsurf'))
        self.layoutWidget = QtGui.QWidget(self.groupBox_urlsurf)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 61))
        self.layoutWidget.setObjectName(_fromUtf8('layoutWidget'))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8('gridLayout_2'))
        self.lineEdit_url_to_surf = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_url_to_surf.sizePolicy().hasHeightForWidth())
        self.lineEdit_url_to_surf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_url_to_surf.setFont(font)
        self.lineEdit_url_to_surf.setReadOnly(True)
        self.lineEdit_url_to_surf.setObjectName(_fromUtf8('lineEdit_url_to_surf'))
        self.gridLayout_2.addWidget(self.lineEdit_url_to_surf, 0, 1, 1, 1)
        self.btn_choose_surf_url = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose_surf_url.sizePolicy().hasHeightForWidth())
        self.btn_choose_surf_url.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_choose_surf_url.setFont(font)
        self.btn_choose_surf_url.setObjectName(_fromUtf8('btn_choose_surf_url'))
        self.gridLayout_2.addWidget(self.btn_choose_surf_url, 0, 2, 1, 1)
        self.label_url = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_url.sizePolicy().hasHeightForWidth())
        self.label_url.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_url.setFont(font)
        self.label_url.setObjectName(_fromUtf8('label_url'))
        self.gridLayout_2.addWidget(self.label_url, 0, 0, 1, 1)
        self.checkBox_proxy = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_proxy.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_proxy.sizePolicy().hasHeightForWidth())
        self.checkBox_proxy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        self.checkBox_proxy.setFont(font)
        self.checkBox_proxy.setObjectName(_fromUtf8('checkBox_proxy'))
        self.gridLayout_2.addWidget(self.checkBox_proxy, 1, 0, 1, 1)
        self.checkBox_download = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_download.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_download.sizePolicy().hasHeightForWidth())
        self.checkBox_download.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        self.checkBox_download.setFont(font)
        self.checkBox_download.setObjectName(_fromUtf8('checkBox_download'))
        self.gridLayout_2.addWidget(self.checkBox_download, 1, 1, 1, 1)
        self.btn_toggle_http_surf = QtGui.QPushButton(self.layoutWidget)
        self.btn_toggle_http_surf.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_http_surf.sizePolicy().hasHeightForWidth())
        self.btn_toggle_http_surf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_toggle_http_surf.setFont(font)
        self.btn_toggle_http_surf.setObjectName(_fromUtf8('btn_toggle_http_surf'))
        self.gridLayout_2.addWidget(self.btn_toggle_http_surf, 1, 2, 1, 1)
        self.groupBox_urlgen = QtGui.QGroupBox(self.tab_surf)
        self.groupBox_urlgen.setGeometry(QtCore.QRect(10, 10, 371, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        self.groupBox_urlgen.setFont(font)
        self.groupBox_urlgen.setObjectName(_fromUtf8('groupBox_urlgen'))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_urlgen)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 351, 61))
        self.layoutWidget1.setObjectName(_fromUtf8('layoutWidget1'))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8('gridLayout'))
        self.lineEdit_surf_site = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_surf_site.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_surf_site.sizePolicy().hasHeightForWidth())
        self.lineEdit_surf_site.setSizePolicy(sizePolicy)
        self.lineEdit_surf_site.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineEdit_surf_site.setBaseSize(QtCore.QSize(1, 0))
        self.lineEdit_surf_site.setReadOnly(True)
        self.lineEdit_surf_site.setObjectName(_fromUtf8('lineEdit_surf_site'))
        self.gridLayout.addWidget(self.lineEdit_surf_site, 0, 1, 1, 1)
        self.label_site = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_site.sizePolicy().hasHeightForWidth())
        self.label_site.setSizePolicy(sizePolicy)
        self.label_site.setObjectName(_fromUtf8('label_site'))
        self.gridLayout.addWidget(self.label_site, 0, 0, 1, 1)
        self.label_urlnum = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_urlnum.sizePolicy().hasHeightForWidth())
        self.label_urlnum.setSizePolicy(sizePolicy)
        self.label_urlnum.setObjectName(_fromUtf8('label_urlnum'))
        self.gridLayout.addWidget(self.label_urlnum, 1, 0, 1, 1)
        self.btn_generate_url = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate_url.sizePolicy().hasHeightForWidth())
        self.btn_generate_url.setSizePolicy(sizePolicy)
        self.btn_generate_url.setMinimumSize(QtCore.QSize(0, 23))
        self.btn_generate_url.setAutoDefault(False)
        self.btn_generate_url.setObjectName(_fromUtf8('btn_generate_url'))
        self.gridLayout.addWidget(self.btn_generate_url, 1, 2, 1, 1)
        self.checkBox_modifysite = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_modifysite.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_modifysite.sizePolicy().hasHeightForWidth())
        self.checkBox_modifysite.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Segoe UI'))
        font.setPointSize(9)
        self.checkBox_modifysite.setFont(font)
        self.checkBox_modifysite.setTristate(False)
        self.checkBox_modifysite.setObjectName(_fromUtf8('checkBox_modifysite'))
        self.gridLayout.addWidget(self.checkBox_modifysite, 0, 2, 1, 1)
        self.spinBox_url_num = QtGui.QSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_url_num.sizePolicy().hasHeightForWidth())
        self.spinBox_url_num.setSizePolicy(sizePolicy)
        self.spinBox_url_num.setMaximum(50000)
        self.spinBox_url_num.setMinimum(1)
        self.spinBox_url_num.setObjectName(_fromUtf8('spinBox_url_num'))
        self.gridLayout.addWidget(self.spinBox_url_num, 1, 1, 1, 1)
        self.groupBox_tosurf = QtGui.QGroupBox(self.tab_surf)
        self.groupBox_tosurf.setGeometry(QtCore.QRect(10, 130, 371, 231))
        self.groupBox_tosurf.setObjectName(_fromUtf8('groupBox_tosurf'))
        self.listWidget_url_to_surf = QtGui.QListWidget(self.groupBox_tosurf)
        self.listWidget_url_to_surf.setGeometry(QtCore.QRect(10, 20, 351, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_url_to_surf.sizePolicy().hasHeightForWidth())
        self.listWidget_url_to_surf.setSizePolicy(sizePolicy)
        self.listWidget_url_to_surf.setResizeMode(QtGui.QListView.Fixed)
        self.listWidget_url_to_surf.setObjectName(_fromUtf8('listWidget_url_to_surf'))
        self.groupBox_finished = QtGui.QGroupBox(self.tab_surf)
        self.groupBox_finished.setGeometry(QtCore.QRect(400, 130, 381, 231))
        self.groupBox_finished.setObjectName(_fromUtf8('groupBox_finished'))
        self.treeWidget_surf_result = QtGui.QTreeWidget(self.groupBox_finished)
        self.treeWidget_surf_result.setGeometry(QtCore.QRect(10, 20, 361, 201))
        self.treeWidget_surf_result.setObjectName(_fromUtf8('treeWidget_surf_result'))
        self.treeItem_s = QtGui.QTreeWidgetItem(self.treeWidget_surf_result)
        self.treeItem_f = QtGui.QTreeWidgetItem(self.treeWidget_surf_result)
        self.progressBar = QtGui.QProgressBar(self.tab_surf)
        self.progressBar.setGeometry(QtCore.QRect(10, 370, 771, 23))
        self.progressBar.setProperty('value', 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8('progressBar'))
        self.tabWidget.addTab(self.tab_surf, _fromUtf8(''))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8('tab'))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 120, 351, 121))
        self.groupBox_4.setObjectName(_fromUtf8('groupBox_4'))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 311, 79))
        self.layoutWidget_2.setObjectName(_fromUtf8('layoutWidget_2'))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8('gridLayout_4'))
        self.btn_popsurf = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_popsurf.sizePolicy().hasHeightForWidth())
        self.btn_popsurf.setSizePolicy(sizePolicy)
        self.btn_popsurf.setObjectName(_fromUtf8('btn_popsurf'))
        self.gridLayout_4.addWidget(self.btn_popsurf, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8('label_3'))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8('label_4'))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_popuser = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_popuser.setEnabled(False)
        self.lineEdit_popuser.setObjectName(_fromUtf8('lineEdit_popuser'))
        self.gridLayout_4.addWidget(self.lineEdit_popuser, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8('label_6'))
        self.gridLayout_4.addWidget(self.label_6, 1, 2, 1, 1)
        self.lineEdit_poppwd = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_poppwd.setEnabled(False)
        self.lineEdit_poppwd.setObjectName(_fromUtf8('lineEdit_poppwd'))
        self.gridLayout_4.addWidget(self.lineEdit_poppwd, 1, 3, 1, 1)
        self.lineEdit_popaddr = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_popaddr.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_popaddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_popaddr.setSizePolicy(sizePolicy)
        self.lineEdit_popaddr.setObjectName(_fromUtf8('lineEdit_popaddr'))
        self.gridLayout_4.addWidget(self.lineEdit_popaddr, 0, 1, 1, 3)
        self.checkBox_pop_emu = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBox_pop_emu.setCheckable(True)
        self.checkBox_pop_emu.setChecked(True)
        self.checkBox_pop_emu.setObjectName(_fromUtf8('checkBox_pop_emu'))
        self.gridLayout_4.addWidget(self.checkBox_pop_emu, 0, 4, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 351, 101))
        self.groupBox_3.setObjectName(_fromUtf8('groupBox_3'))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 311, 79))
        self.layoutWidget2.setObjectName(_fromUtf8('layoutWidget2'))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8('gridLayout_3'))
        self.btn_ftpsurf = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ftpsurf.sizePolicy().hasHeightForWidth())
        self.btn_ftpsurf.setSizePolicy(sizePolicy)
        self.btn_ftpsurf.setObjectName(_fromUtf8('btn_ftpsurf'))
        self.gridLayout_3.addWidget(self.btn_ftpsurf, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8('label'))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8('label_2'))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_ftpuser = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_ftpuser.setEnabled(False)
        self.lineEdit_ftpuser.setObjectName(_fromUtf8('lineEdit_ftpuser'))
        self.gridLayout_3.addWidget(self.lineEdit_ftpuser, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8('label_5'))
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.lineEdit_ftppwd = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_ftppwd.setEnabled(False)
        self.lineEdit_ftppwd.setObjectName(_fromUtf8('lineEdit_ftppwd'))
        self.gridLayout_3.addWidget(self.lineEdit_ftppwd, 1, 3, 1, 1)
        self.lineEdit_ftpaddr = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_ftpaddr.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ftpaddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_ftpaddr.setSizePolicy(sizePolicy)
        self.lineEdit_ftpaddr.setObjectName(_fromUtf8('lineEdit_ftpaddr'))
        self.gridLayout_3.addWidget(self.lineEdit_ftpaddr, 0, 1, 1, 3)
        self.checkBox_ftp_emu = QtGui.QCheckBox(self.layoutWidget2)
        self.checkBox_ftp_emu.setCheckable(True)
        self.checkBox_ftp_emu.setChecked(True)
        self.checkBox_ftp_emu.setObjectName(_fromUtf8('checkBox_ftp_emu'))
        self.gridLayout_3.addWidget(self.checkBox_ftp_emu, 0, 4, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 120, 361, 121))
        self.groupBox_5.setObjectName(_fromUtf8('groupBox_5'))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 30, 321, 79))
        self.layoutWidget_3.setObjectName(_fromUtf8('layoutWidget_3'))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8('gridLayout_5'))
        self.btn_smtpsurf = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_smtpsurf.sizePolicy().hasHeightForWidth())
        self.btn_smtpsurf.setSizePolicy(sizePolicy)
        self.btn_smtpsurf.setObjectName(_fromUtf8('btn_smtpsurf'))
        self.gridLayout_5.addWidget(self.btn_smtpsurf, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8('label_7'))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8('label_8'))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_smtpuser = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEdit_smtpuser.setEnabled(False)
        self.lineEdit_smtpuser.setObjectName(_fromUtf8('lineEdit_smtpuser'))
        self.gridLayout_5.addWidget(self.lineEdit_smtpuser, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8('label_9'))
        self.gridLayout_5.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEdit_smtppwd = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEdit_smtppwd.setEnabled(False)
        self.lineEdit_smtppwd.setObjectName(_fromUtf8('lineEdit_smtppwd'))
        self.gridLayout_5.addWidget(self.lineEdit_smtppwd, 1, 3, 1, 1)
        self.lineEdit_smtpaddr = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEdit_smtpaddr.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_smtpaddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_smtpaddr.setSizePolicy(sizePolicy)
        self.lineEdit_smtpaddr.setObjectName(_fromUtf8('lineEdit_smtpaddr'))
        self.gridLayout_5.addWidget(self.lineEdit_smtpaddr, 0, 1, 1, 3)
        self.checkBox_smtp_emu = QtGui.QCheckBox(self.layoutWidget_3)
        self.checkBox_smtp_emu.setCheckable(True)
        self.checkBox_smtp_emu.setChecked(True)
        self.checkBox_smtp_emu.setObjectName(_fromUtf8('checkBox_smtp_emu'))
        self.gridLayout_5.addWidget(self.checkBox_smtp_emu, 0, 4, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(400, 10, 361, 101))
        self.groupBox_6.setObjectName(_fromUtf8('groupBox_6'))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 321, 79))
        self.layoutWidget_4.setObjectName(_fromUtf8('layoutWidget_4'))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8('gridLayout_6'))
        self.btn_snmpsurf = QtGui.QPushButton(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_snmpsurf.sizePolicy().hasHeightForWidth())
        self.btn_snmpsurf.setSizePolicy(sizePolicy)
        self.btn_snmpsurf.setObjectName(_fromUtf8('btn_snmpsurf'))
        self.gridLayout_6.addWidget(self.btn_snmpsurf, 1, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8('label_10'))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8('label_11'))
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_snmpuser = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit_snmpuser.setEnabled(False)
        self.lineEdit_snmpuser.setObjectName(_fromUtf8('lineEdit_snmpuser'))
        self.gridLayout_6.addWidget(self.lineEdit_snmpuser, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_4)
        self.label_12.setObjectName(_fromUtf8('label_12'))
        self.gridLayout_6.addWidget(self.label_12, 1, 2, 1, 1)
        self.lineEdit_snmppwd = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit_snmppwd.setEnabled(False)
        self.lineEdit_snmppwd.setObjectName(_fromUtf8('lineEdit_snmppwd'))
        self.gridLayout_6.addWidget(self.lineEdit_snmppwd, 1, 3, 1, 1)
        self.lineEdit_snmpaddr = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit_snmpaddr.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_snmpaddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_snmpaddr.setSizePolicy(sizePolicy)
        self.lineEdit_snmpaddr.setObjectName(_fromUtf8('lineEdit_snmpaddr'))
        self.gridLayout_6.addWidget(self.lineEdit_snmpaddr, 0, 1, 1, 3)
        self.checkBox_snmp_emu = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBox_snmp_emu.setCheckable(True)
        self.checkBox_snmp_emu.setChecked(True)
        self.checkBox_snmp_emu.setObjectName(_fromUtf8('checkBox_snmp_emu'))
        self.gridLayout_6.addWidget(self.checkBox_snmp_emu, 0, 4, 1, 1)
        self.textEdit_other_surf_result = QtGui.QTextEdit(self.tab)
        self.textEdit_other_surf_result.setGeometry(QtCore.QRect(20, 250, 741, 151))
        self.textEdit_other_surf_result.setObjectName(_fromUtf8('textEdit_other_surf_result'))
        self.tabWidget.addTab(self.tab, _fromUtf8(''))
        self.tab_compare = QtGui.QWidget()
        self.tab_compare.setObjectName(_fromUtf8('tab_compare'))
        self.groupBox_path = QtGui.QGroupBox(self.tab_compare)
        self.groupBox_path.setGeometry(QtCore.QRect(10, 10, 771, 71))
        self.groupBox_path.setObjectName(_fromUtf8('groupBox_path'))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_path)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 26, 751, 31))
        self.layoutWidget3.setObjectName(_fromUtf8('layoutWidget3'))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8('horizontalLayout'))
        self.label_surfurl = QtGui.QLabel(self.layoutWidget3)
        self.label_surfurl.setObjectName(_fromUtf8('label_surfurl'))
        self.horizontalLayout.addWidget(self.label_surfurl)
        self.lineEdit_success_url = QtGui.QLineEdit(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_success_url.sizePolicy().hasHeightForWidth())
        self.lineEdit_success_url.setSizePolicy(sizePolicy)
        self.lineEdit_success_url.setReadOnly(True)
        self.lineEdit_success_url.setObjectName(_fromUtf8('lineEdit_success_url'))
        self.horizontalLayout.addWidget(self.lineEdit_success_url)
        self.btn_choose_success_url = QtGui.QPushButton(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose_success_url.sizePolicy().hasHeightForWidth())
        self.btn_choose_success_url.setSizePolicy(sizePolicy)
        self.btn_choose_success_url.setObjectName(_fromUtf8('btn_choose_success_url'))
        self.horizontalLayout.addWidget(self.btn_choose_success_url)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_successurl = QtGui.QLabel(self.layoutWidget3)
        self.label_successurl.setObjectName(_fromUtf8('label_successurl'))
        self.horizontalLayout.addWidget(self.label_successurl)
        self.lineEdit_log_url = QtGui.QLineEdit(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_log_url.sizePolicy().hasHeightForWidth())
        self.lineEdit_log_url.setSizePolicy(sizePolicy)
        self.lineEdit_log_url.setReadOnly(True)
        self.lineEdit_log_url.setObjectName(_fromUtf8('lineEdit_log_url'))
        self.horizontalLayout.addWidget(self.lineEdit_log_url)
        self.btn_choose_log_url = QtGui.QPushButton(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose_log_url.sizePolicy().hasHeightForWidth())
        self.btn_choose_log_url.setSizePolicy(sizePolicy)
        self.btn_choose_log_url.setObjectName(_fromUtf8('btn_choose_log_url'))
        self.horizontalLayout.addWidget(self.btn_choose_log_url)
        self.groupBox_result = QtGui.QGroupBox(self.tab_compare)
        self.groupBox_result.setGeometry(QtCore.QRect(10, 90, 771, 271))
        self.groupBox_result.setObjectName(_fromUtf8('groupBox_result'))
        self.textEdit_compare_result = QtGui.QTextEdit(self.groupBox_result)
        self.textEdit_compare_result.setGeometry(QtCore.QRect(10, 20, 751, 241))
        self.textEdit_compare_result.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit_compare_result.setObjectName(_fromUtf8('textEdit_compare_result'))
        self.layoutWidget4 = QtGui.QWidget(self.tab_compare)
        self.layoutWidget4.setGeometry(QtCore.QRect(300, 370, 183, 31))
        self.layoutWidget4.setObjectName(_fromUtf8('layoutWidget4'))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8('horizontalLayout_2'))
        self.btn_compare = QtGui.QPushButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_compare.sizePolicy().hasHeightForWidth())
        self.btn_compare.setSizePolicy(sizePolicy)
        self.btn_compare.setObjectName(_fromUtf8('btn_compare'))
        self.horizontalLayout_2.addWidget(self.btn_compare)
        self.btn_save = QtGui.QPushButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName(_fromUtf8('btn_save'))
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.tabWidget.addTab(self.tab_compare, _fromUtf8(''))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 23))
        self.menubar.setObjectName(_fromUtf8('menubar'))
        self.menu_setting = QtGui.QMenu(self.menubar)
        self.menu_setting.setEnabled(True)
        self.menu_setting.setObjectName(_fromUtf8('menu_setting'))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8('menu_help'))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8('statusbar'))
        MainWindow.setStatusBar(self.statusbar)
        self.action_update = QtGui.QAction(MainWindow)
        self.action_update.setObjectName(_fromUtf8('action_update'))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8('action_about'))
        self.action_setdir = QtGui.QAction(MainWindow)
        self.action_setdir.setIconVisibleInMenu(False)
        self.action_setdir.setObjectName(_fromUtf8('action_setdir'))
        self.action_setproxy = QtGui.QAction(MainWindow)
        self.action_setproxy.setIconVisibleInMenu(False)
        self.action_setproxy.setObjectName(_fromUtf8('action_setproxy'))
        self.menu_setting.addAction(self.action_setproxy)
        self.menu_setting.addAction(self.action_setdir)
        self.menu_help.addAction(self.action_update)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_setting.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox_snmp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_snmpaddr.setDisabled)
        QtCore.QObject.connect(self.checkBox_snmp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_snmppwd.setDisabled)
        QtCore.QObject.connect(self.checkBox_snmp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_snmpuser.setDisabled)
        QtCore.QObject.connect(self.checkBox_ftp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_ftpaddr.setDisabled)
        QtCore.QObject.connect(self.checkBox_ftp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_ftppwd.setDisabled)
        QtCore.QObject.connect(self.checkBox_ftp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_ftpuser.setDisabled)
        QtCore.QObject.connect(self.checkBox_pop_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_popaddr.setDisabled)
        QtCore.QObject.connect(self.checkBox_pop_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_poppwd.setDisabled)
        QtCore.QObject.connect(self.checkBox_smtp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_smtpuser.setDisabled)
        QtCore.QObject.connect(self.checkBox_pop_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_popuser.setDisabled)
        QtCore.QObject.connect(self.checkBox_smtp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_smtpaddr.setDisabled)
        QtCore.QObject.connect(self.checkBox_smtp_emu, QtCore.SIGNAL(_fromUtf8('clicked(bool)')), self.lineEdit_smtppwd.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_surf_site)
        MainWindow.setTabOrder(self.lineEdit_surf_site, self.checkBox_modifysite)
        MainWindow.setTabOrder(self.checkBox_modifysite, self.spinBox_url_num)
        MainWindow.setTabOrder(self.spinBox_url_num, self.btn_generate_url)
        MainWindow.setTabOrder(self.btn_generate_url, self.lineEdit_url_to_surf)
        MainWindow.setTabOrder(self.lineEdit_url_to_surf, self.btn_choose_surf_url)
        MainWindow.setTabOrder(self.btn_choose_surf_url, self.checkBox_proxy)
        MainWindow.setTabOrder(self.checkBox_proxy, self.checkBox_download)
        MainWindow.setTabOrder(self.checkBox_download, self.btn_toggle_http_surf)
        MainWindow.setTabOrder(self.btn_toggle_http_surf, self.listWidget_url_to_surf)
        MainWindow.setTabOrder(self.listWidget_url_to_surf, self.treeWidget_surf_result)
        MainWindow.setTabOrder(self.treeWidget_surf_result, self.lineEdit_success_url)
        MainWindow.setTabOrder(self.lineEdit_success_url, self.btn_choose_success_url)
        MainWindow.setTabOrder(self.btn_choose_success_url, self.lineEdit_log_url)
        MainWindow.setTabOrder(self.lineEdit_log_url, self.btn_choose_log_url)
        MainWindow.setTabOrder(self.btn_choose_log_url, self.textEdit_compare_result)
        MainWindow.setTabOrder(self.textEdit_compare_result, self.btn_compare)
        MainWindow.setTabOrder(self.btn_compare, self.btn_save)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate('MainWindow', '\xe7\xbb\xbc\xe5\x90\x88\xe6\x8b\xa8\xe6\xb5\x8b\xe5\xb7\xa5\xe5\x85\xb7', None))
        self.groupBox_urlsurf.setTitle(_translate('MainWindow', '\xe6\x8b\xa8\xe6\xb5\x8b\xe9\x80\x89\xe9\xa1\xb9', None))
        self.btn_choose_surf_url.setStatusTip(_translate('MainWindow', 'URL\xe9\x9c\x80\xe5\x8c\x85\xe5\x90\xabhttp://\xe5\x8d\x8f\xe8\xae\xae\xe5\xa4\xb4', None))
        self.btn_choose_surf_url.setText(_translate('MainWindow', '\xe9\x80\x89  \xe6\x8b\xa9..', None))
        self.label_url.setText(_translate('MainWindow', 'URL\xe5\x88\x97\xe8\xa1\xa8\xef\xbc\x9a', None))
        self.checkBox_proxy.setText(_translate('MainWindow', '\xe4\xbb\xa3\xe7\x90\x86\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.checkBox_download.setText(_translate('MainWindow', '\xe4\xb8\x8b\xe8\xbd\xbd\xe6\x8b\xa8\xe6\xb5\x8b\xe9\xa1\xb5\xe9\x9d\xa2', None))
        self.btn_toggle_http_surf.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b', None))
        self.groupBox_urlgen.setTitle(_translate('MainWindow', '\xe5\x8f\x82\xe8\x80\x83\xe7\xab\x99URL\xe7\x94\x9f\xe6\x88\x90', None))
        self.label_site.setText(_translate('MainWindow', '\xe5\x8f\x82\xe8\x80\x83\xe7\xbd\x91\xe7\xab\x99\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a', None))
        self.label_urlnum.setText(_translate('MainWindow', 'URL\xe7\x94\x9f\xe6\x88\x90\xe6\x95\xb0\xe9\x87\x8f\xef\xbc\x9a', None))
        self.btn_generate_url.setText(_translate('MainWindow', '\xe7\x94\x9f\xe6\x88\x90', None))
        self.checkBox_modifysite.setText(_translate('MainWindow', '\xe4\xbf\xae\xe6\x94\xb9\xe5\x9c\xb0\xe5\x9d\x80', None))
        self.groupBox_tosurf.setTitle(_translate('MainWindow', '\xe5\xbe\x85\xe6\x8b\xa8\xe6\xb5\x8bRURL', None))
        self.groupBox_finished.setTitle(_translate('MainWindow', '\xe5\xb7\xb2\xe6\x8b\xa8\xe6\xb5\x8bURL', None))
        self.treeWidget_surf_result.headerItem().setText(0, _translate('MainWindow', 'URL', None))
        __sortingEnabled = self.treeWidget_surf_result.isSortingEnabled()
        self.treeWidget_surf_result.setSortingEnabled(False)
        self.treeWidget_surf_result.topLevelItem(0).setText(0, _translate('MainWindow', 'Success', None))
        self.treeWidget_surf_result.topLevelItem(1).setText(0, _translate('MainWindow', 'Failed', None))
        self.treeWidget_surf_result.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_surf), _translate('MainWindow', 'HTTP\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.groupBox_4.setTitle(_translate('MainWindow', 'POP\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.btn_popsurf.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b', None))
        self.label_3.setText(_translate('MainWindow', '\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a', None))
        self.label_4.setText(_translate('MainWindow', '\xe7\x94\xa8\xe6\x88\xb7\xef\xbc\x9a', None))
        self.label_6.setText(_translate('MainWindow', '\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a', None))
        self.checkBox_pop_emu.setText(_translate('MainWindow', '\xe6\xa8\xa1\xe6\x8b\x9f\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.groupBox_3.setTitle(_translate('MainWindow', 'FTP\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.btn_ftpsurf.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b', None))
        self.label.setText(_translate('MainWindow', '\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a', None))
        self.label_2.setText(_translate('MainWindow', '\xe7\x94\xa8\xe6\x88\xb7\xef\xbc\x9a', None))
        self.label_5.setText(_translate('MainWindow', '\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a', None))
        self.checkBox_ftp_emu.setText(_translate('MainWindow', '\xe6\xa8\xa1\xe6\x8b\x9f\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.groupBox_5.setTitle(_translate('MainWindow', 'SMTP\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.btn_smtpsurf.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b', None))
        self.label_7.setText(_translate('MainWindow', '\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a', None))
        self.label_8.setText(_translate('MainWindow', '\xe7\x94\xa8\xe6\x88\xb7\xef\xbc\x9a', None))
        self.label_9.setText(_translate('MainWindow', '\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a', None))
        self.checkBox_smtp_emu.setText(_translate('MainWindow', '\xe6\xa8\xa1\xe6\x8b\x9f\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.groupBox_6.setTitle(_translate('MainWindow', 'SNMP\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.btn_snmpsurf.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b', None))
        self.label_10.setText(_translate('MainWindow', '\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a', None))
        self.label_11.setText(_translate('MainWindow', '\xe7\x94\xa8\xe6\x88\xb7\xef\xbc\x9a', None))
        self.label_12.setText(_translate('MainWindow', '\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a', None))
        self.checkBox_snmp_emu.setText(_translate('MainWindow', '\xe6\xa8\xa1\xe6\x8b\x9f\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate('MainWindow', '\xe5\x85\xb6\xe4\xbb\x96\xe6\x8b\xa8\xe6\xb5\x8b', None))
        self.groupBox_path.setTitle(_translate('MainWindow', '\xe5\xaf\xb9\xe6\xaf\x94\xe9\x80\x89\xe9\xa1\xb9', None))
        self.label_surfurl.setText(_translate('MainWindow', '\xe6\x8b\xa8\xe6\xb5\x8b\xe6\x88\x90\xe5\x8a\x9fURL\xe5\x88\x97\xe8\xa1\xa8\xef\xbc\x9a', None))
        self.btn_choose_success_url.setText(_translate('MainWindow', '\xe9\x80\x89  \xe6\x8b\xa9..', None))
        self.label_successurl.setText(_translate('MainWindow', '\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xae\xb0\xe5\xbd\x95URL\xe5\x88\x97\xe8\xa1\xa8\xef\xbc\x9a', None))
        self.btn_choose_log_url.setText(_translate('MainWindow', '\xe9\x80\x89  \xe6\x8b\xa9..', None))
        self.groupBox_result.setTitle(_translate('MainWindow', '\xe5\xaf\xb9\xe6\xaf\x94\xe7\xbb\x93\xe6\x9e\x9c', None))
        self.btn_compare.setStatusTip(_translate('MainWindow', 'URL\xe9\x9c\x80\xe5\x8c\x85\xe5\x90\xabhttp://\xe5\x8d\x8f\xe8\xae\xae\xe5\xa4\xb4', None))
        self.btn_compare.setText(_translate('MainWindow', '\xe5\xbc\x80\xe5\xa7\x8b\xe5\xaf\xb9\xe6\xaf\x94', None))
        self.btn_save.setText(_translate('MainWindow', '\xe4\xbf\x9d\xe5\xad\x98\xe7\xbb\x93\xe6\x9e\x9c', None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_compare), _translate('MainWindow', '\xe6\x95\xb0\xe6\x8d\xae\xe5\xaf\xb9\xe6\xaf\x94', None))
        self.menu_setting.setTitle(_translate('MainWindow', '\xe8\xae\xbe\xe7\xbd\xae(&S)', None))
        self.menu_help.setTitle(_translate('MainWindow', '\xe5\xb8\xae\xe5\x8a\xa9(&H)', None))
        self.action_update.setText(_translate('MainWindow', '\xe6\xa3\x80\xe6\x9f\xa5\xe6\x9b\xb4\xe6\x96\xb0(&U)', None))
        self.action_update.setStatusTip(_translate('MainWindow', '\xe6\xa3\x80\xe6\x9f\xa5\xe5\xb9\xb6\xe6\x9b\xb4\xe6\x96\xb0\xe8\xbd\xaf\xe4\xbb\xb6', None))
        self.action_about.setText(_translate('MainWindow', '\xe5\x85\xb3\xe4\xba\x8e', None))
        self.action_about.setStatusTip(_translate('MainWindow', '\xe8\xbd\xaf\xe4\xbb\xb6\xe4\xbf\xa1\xe6\x81\xaf', None))
        self.action_setdir.setText(_translate('MainWindow', '\xe7\x9b\xae\xe5\xbd\x95\xe9\x85\x8d\xe7\xbd\xae(&D)', None))
        self.action_setdir.setStatusTip(_translate('MainWindow', '\xe9\x85\x8d\xe7\xbd\xae\xe6\x97\xa5\xe5\xbf\x97\xe5\xad\x98\xe6\x94\xbe\xe7\x9b\xae\xe5\xbd\x95', None))
        self.action_setproxy.setText(_translate('MainWindow', '\xe6\x8b\xa8\xe6\xb5\x8b\xe9\x85\x8d\xe7\xbd\xae(&S)', None))
        self.action_setproxy.setStatusTip(_translate('MainWindow', '\xe9\x85\x8d\xe7\xbd\xae\xe6\x8b\xa8\xe6\xb5\x8b\xe9\x80\x89\xe9\xa1\xb9', None))
        return